-- ============================================================
-- ACTUALIZACIÓN DE CHUNKS DESCRIPTIVOS - TRÉBOL MOTORS
-- Ejecutar este script ANTES de regenerar embeddings
-- ============================================================

BEGIN;

UPDATE vec_vehiculo_descripcion SET chunk_texto = $$Mazda CX-5 2025 gris plata mecánica hibrido 2L suv 17.977 km estado excelente$$ WHERE id_vehiculo = 1;
UPDATE vec_vehiculo_descripcion SET chunk_texto = $$Toyota Fortuner 2020 gris plata automática hibrido 2.5L sedan 74.555 km estado excelente$$ WHERE id_vehiculo = 2;
UPDATE vec_vehiculo_descripcion SET chunk_texto = $$Mazda CX-30 2023 gris plata mecánica diesel 1.6L sedan 62.437 km estado bueno$$ WHERE id_vehiculo = 3;
UPDATE vec_vehiculo_descripcion SET chunk_texto = $$Renault Kwid 2024 negro mecánica hibrido 2L pickup 26.405 km estado bueno$$ WHERE id_vehiculo = 4;
UPDATE vec_vehiculo_descripcion SET chunk_texto = $$Renault Logan 2020 azul profundo mecánica diesel 2.5L hatchback 15.823 km estado excelente$$ WHERE id_vehiculo = 5;
UPDATE vec_vehiculo_descripcion SET chunk_texto = $$Mazda CX-30 2018 negro automática diesel 2.5L hatchback 45.249 km estado bueno$$ WHERE id_vehiculo = 6;
UPDATE vec_vehiculo_descripcion SET chunk_texto = $$Mazda Mazda 2 2025 rojo milano automática diesel 2L suv 22.435 km estado muy_bueno$$ WHERE id_vehiculo = 7;
UPDATE vec_vehiculo_descripcion SET chunk_texto = $$Chevrolet Captiva 2022 azul profundo mecánica diesel 2L suv 89.024 km estado bueno$$ WHERE id_vehiculo = 8;
UPDATE vec_vehiculo_descripcion SET chunk_texto = $$Toyota Hilux 2021 azul profundo mecánica diesel 2L pickup 79.943 km estado bueno$$ WHERE id_vehiculo = 9;
UPDATE vec_vehiculo_descripcion SET chunk_texto = $$Renault Duster 2022 negro automática hibrido 1.6L suv 75.031 km estado excelente$$ WHERE id_vehiculo = 10;
UPDATE vec_vehiculo_descripcion SET chunk_texto = $$Chevrolet Captiva 2024 gris plata automática diesel 1.6L pickup 70.230 km estado excelente$$ WHERE id_vehiculo = 11;
UPDATE vec_vehiculo_descripcion SET chunk_texto = $$Toyota Fortuner 2019 rojo milano mecánica hibrido 2L hatchback 78.419 km estado excelente$$ WHERE id_vehiculo = 12;
UPDATE vec_vehiculo_descripcion SET chunk_texto = $$Renault Kwid 2022 rojo milano mecánica gasolina 1.6L pickup 52.893 km estado bueno$$ WHERE id_vehiculo = 13;
UPDATE vec_vehiculo_descripcion SET chunk_texto = $$Renault Duster 2021 azul profundo automática diesel 2.5L pickup 89.823 km estado excelente$$ WHERE id_vehiculo = 14;
UPDATE vec_vehiculo_descripcion SET chunk_texto = $$Renault Duster 2022 negro mecánica gasolina 2L hatchback 24.326 km estado excelente$$ WHERE id_vehiculo = 15;
UPDATE vec_vehiculo_descripcion SET chunk_texto = $$Chevrolet Onix 2023 rojo milano automática hibrido 1.6L hatchback 12.434 km estado bueno$$ WHERE id_vehiculo = 16;
UPDATE vec_vehiculo_descripcion SET chunk_texto = $$Chevrolet Onix 2025 negro automática gasolina 2.5L sedan 7.942 km estado excelente$$ WHERE id_vehiculo = 17;
UPDATE vec_vehiculo_descripcion SET chunk_texto = $$Mazda CX-30 2019 gris plata automática hibrido 1.6L camioneta 19.509 km estado muy_bueno$$ WHERE id_vehiculo = 18;
UPDATE vec_vehiculo_descripcion SET chunk_texto = $$Mazda Mazda 2 2025 azul profundo automática hibrido 2.5L suv 64.192 km estado muy_bueno$$ WHERE id_vehiculo = 19;
UPDATE vec_vehiculo_descripcion SET chunk_texto = $$Renault Sandero 2021 gris plata mecánica hibrido 1.6L camioneta 40.451 km estado muy_bueno$$ WHERE id_vehiculo = 20;
UPDATE vec_vehiculo_descripcion SET chunk_texto = $$Mazda CX-30 2020 azul profundo automática gasolina 1.6L hatchback 30.296 km estado excelente$$ WHERE id_vehiculo = 21;
UPDATE vec_vehiculo_descripcion SET chunk_texto = $$Renault Sandero 2018 negro mecánica hibrido 2.5L hatchback 54.174 km estado muy_bueno$$ WHERE id_vehiculo = 22;
UPDATE vec_vehiculo_descripcion SET chunk_texto = $$Mazda CX-30 2020 azul profundo mecánica hibrido 1.6L camioneta 33.082 km estado bueno$$ WHERE id_vehiculo = 23;
UPDATE vec_vehiculo_descripcion SET chunk_texto = $$Renault Logan 2025 negro mecánica gasolina 2.5L camioneta 23.975 km estado muy_bueno$$ WHERE id_vehiculo = 24;
UPDATE vec_vehiculo_descripcion SET chunk_texto = $$Mazda CX-5 2018 gris plata automática diesel 2L suv 20.622 km estado muy_bueno$$ WHERE id_vehiculo = 25;
UPDATE vec_vehiculo_descripcion SET chunk_texto = $$Toyota Hilux 2019 rojo milano automática gasolina 1.6L pickup 25.283 km estado bueno$$ WHERE id_vehiculo = 26;
UPDATE vec_vehiculo_descripcion SET chunk_texto = $$Mazda CX-30 2018 blanco mecánica diesel 2L suv 15.505 km estado muy_bueno$$ WHERE id_vehiculo = 27;
UPDATE vec_vehiculo_descripcion SET chunk_texto = $$Chevrolet Onix 2022 blanco automática gasolina 2L pickup 56.336 km estado excelente$$ WHERE id_vehiculo = 28;
UPDATE vec_vehiculo_descripcion SET chunk_texto = $$Toyota Hilux 2025 azul profundo automática hibrido 2.5L hatchback 55.178 km estado muy_bueno$$ WHERE id_vehiculo = 29;
UPDATE vec_vehiculo_descripcion SET chunk_texto = $$Renault Kwid 2022 negro automática gasolina 2.5L camioneta 48.939 km estado bueno$$ WHERE id_vehiculo = 30;
UPDATE vec_vehiculo_descripcion SET chunk_texto = $$Toyota Hilux 2021 negro mecánica hibrido 1.6L hatchback 59.895 km estado excelente$$ WHERE id_vehiculo = 31;
UPDATE vec_vehiculo_descripcion SET chunk_texto = $$Toyota Yaris 2019 rojo milano mecánica diesel 2L camioneta 77.988 km estado excelente$$ WHERE id_vehiculo = 32;
UPDATE vec_vehiculo_descripcion SET chunk_texto = $$Chevrolet Onix 2025 negro automática gasolina 2L hatchback 42.926 km estado muy_bueno$$ WHERE id_vehiculo = 33;
UPDATE vec_vehiculo_descripcion SET chunk_texto = $$Chevrolet Colorado 2023 rojo milano automática gasolina 2.5L suv 16.782 km estado excelente$$ WHERE id_vehiculo = 34;
UPDATE vec_vehiculo_descripcion SET chunk_texto = $$Mazda Mazda 3 2022 rojo milano mecánica diesel 2.5L suv 9.006 km estado excelente$$ WHERE id_vehiculo = 35;
UPDATE vec_vehiculo_descripcion SET chunk_texto = $$Chevrolet Onix 2024 azul profundo mecánica gasolina 1.6L hatchback 5.938 km estado muy_bueno$$ WHERE id_vehiculo = 36;
UPDATE vec_vehiculo_descripcion SET chunk_texto = $$Renault Kwid 2022 negro mecánica gasolina 2L sedan 49.691 km estado excelente$$ WHERE id_vehiculo = 37;
UPDATE vec_vehiculo_descripcion SET chunk_texto = $$Toyota Corolla 2023 negro automática gasolina 2L pickup 24.850 km estado muy_bueno$$ WHERE id_vehiculo = 38;
UPDATE vec_vehiculo_descripcion SET chunk_texto = $$Chevrolet Colorado 2024 azul profundo automática gasolina 2L sedan 29.484 km estado muy_bueno$$ WHERE id_vehiculo = 39;
UPDATE vec_vehiculo_descripcion SET chunk_texto = $$Mazda Mazda 2 2021 azul profundo automática diesel 2L pickup 61.174 km estado excelente$$ WHERE id_vehiculo = 40;
UPDATE vec_vehiculo_descripcion SET chunk_texto = $$Chevrolet Colorado 2021 blanco automática gasolina 2L sedan 14.114 km estado bueno$$ WHERE id_vehiculo = 41;
UPDATE vec_vehiculo_descripcion SET chunk_texto = $$Chevrolet Captiva 2021 negro automática hibrido 1.6L sedan 56.760 km estado excelente$$ WHERE id_vehiculo = 42;
UPDATE vec_vehiculo_descripcion SET chunk_texto = $$Mazda Mazda 3 2025 negro mecánica hibrido 1.6L suv 19.543 km estado muy_bueno$$ WHERE id_vehiculo = 43;
UPDATE vec_vehiculo_descripcion SET chunk_texto = $$Toyota Fortuner 2022 gris plata automática hibrido 2.5L sedan 71.816 km estado muy_bueno$$ WHERE id_vehiculo = 44;
UPDATE vec_vehiculo_descripcion SET chunk_texto = $$Mazda Mazda 3 2021 gris plata automática gasolina 2.5L suv 47.662 km estado muy_bueno$$ WHERE id_vehiculo = 45;
UPDATE vec_vehiculo_descripcion SET chunk_texto = $$Toyota Fortuner 2020 azul profundo automática gasolina 2.5L hatchback 18.271 km estado excelente$$ WHERE id_vehiculo = 46;
UPDATE vec_vehiculo_descripcion SET chunk_texto = $$Toyota Fortuner 2020 rojo milano mecánica gasolina 2L hatchback 37.296 km estado muy_bueno$$ WHERE id_vehiculo = 47;
UPDATE vec_vehiculo_descripcion SET chunk_texto = $$Chevrolet Colorado 2021 negro mecánica diesel 1.6L suv 74.108 km estado excelente$$ WHERE id_vehiculo = 48;
UPDATE vec_vehiculo_descripcion SET chunk_texto = $$Mazda CX-30 2018 negro mecánica diesel 2L hatchback 59.287 km estado excelente$$ WHERE id_vehiculo = 49;
UPDATE vec_vehiculo_descripcion SET chunk_texto = $$Renault Sandero 2023 azul profundo automática gasolina 2L pickup 67.005 km estado muy_bueno$$ WHERE id_vehiculo = 50;
UPDATE vec_vehiculo_descripcion SET chunk_texto = $$Chevrolet Tracker 2025 gris plata mecánica diesel 1.6L camioneta 34.232 km estado excelente$$ WHERE id_vehiculo = 51;
UPDATE vec_vehiculo_descripcion SET chunk_texto = $$Mazda Mazda 3 2024 blanco mecánica gasolina 2L pickup 42.278 km estado bueno$$ WHERE id_vehiculo = 52;
UPDATE vec_vehiculo_descripcion SET chunk_texto = $$Toyota Yaris 2020 rojo milano mecánica diesel 1.6L pickup 17.522 km estado muy_bueno$$ WHERE id_vehiculo = 53;
UPDATE vec_vehiculo_descripcion SET chunk_texto = $$Renault Sandero 2023 gris plata mecánica hibrido 2.5L hatchback 79.360 km estado excelente$$ WHERE id_vehiculo = 54;
UPDATE vec_vehiculo_descripcion SET chunk_texto = $$Chevrolet Colorado 2018 blanco automática diesel 2.5L pickup 56.922 km estado muy_bueno$$ WHERE id_vehiculo = 55;
UPDATE vec_vehiculo_descripcion SET chunk_texto = $$Chevrolet Onix 2018 azul profundo mecánica hibrido 2.5L hatchback 84.250 km estado muy_bueno$$ WHERE id_vehiculo = 56;
UPDATE vec_vehiculo_descripcion SET chunk_texto = $$Mazda Mazda 2 2023 negro mecánica diesel 1.6L camioneta 23.009 km estado bueno$$ WHERE id_vehiculo = 57;
UPDATE vec_vehiculo_descripcion SET chunk_texto = $$Mazda CX-30 2018 negro mecánica hibrido 1.6L suv 15.385 km estado muy_bueno$$ WHERE id_vehiculo = 58;
UPDATE vec_vehiculo_descripcion SET chunk_texto = $$Toyota Hilux 2024 gris plata automática gasolina 2.5L suv 67.930 km estado bueno$$ WHERE id_vehiculo = 59;
UPDATE vec_vehiculo_descripcion SET chunk_texto = $$Mazda Mazda 2 2023 gris plata automática hibrido 2L sedan 83.159 km estado muy_bueno$$ WHERE id_vehiculo = 60;
UPDATE vec_vehiculo_descripcion SET chunk_texto = $$Mazda Mazda 2 2018 blanco automática hibrido 2L pickup 69.224 km estado excelente$$ WHERE id_vehiculo = 61;
UPDATE vec_vehiculo_descripcion SET chunk_texto = $$Toyota Hilux 2024 blanco mecánica hibrido 2.5L hatchback 80.939 km estado bueno$$ WHERE id_vehiculo = 62;
UPDATE vec_vehiculo_descripcion SET chunk_texto = $$Mazda CX-30 2025 blanco automática hibrido 2.5L hatchback 87.722 km estado muy_bueno$$ WHERE id_vehiculo = 63;
UPDATE vec_vehiculo_descripcion SET chunk_texto = $$Chevrolet Tracker 2021 negro automática diesel 2.5L camioneta 86.579 km estado bueno$$ WHERE id_vehiculo = 64;
UPDATE vec_vehiculo_descripcion SET chunk_texto = $$Renault Kwid 2022 gris plata mecánica gasolina 2.5L pickup 18.858 km estado excelente$$ WHERE id_vehiculo = 65;
UPDATE vec_vehiculo_descripcion SET chunk_texto = $$Chevrolet Colorado 2021 blanco mecánica hibrido 1.6L pickup 75.393 km estado muy_bueno$$ WHERE id_vehiculo = 66;
UPDATE vec_vehiculo_descripcion SET chunk_texto = $$Mazda CX-5 2023 azul profundo mecánica diesel 2.5L suv 70.665 km estado bueno$$ WHERE id_vehiculo = 67;
UPDATE vec_vehiculo_descripcion SET chunk_texto = $$Mazda CX-5 2018 negro mecánica hibrido 2L pickup 68.144 km estado bueno$$ WHERE id_vehiculo = 68;
UPDATE vec_vehiculo_descripcion SET chunk_texto = $$Toyota Hilux 2023 rojo milano mecánica hibrido 1.6L sedan 84.559 km estado bueno$$ WHERE id_vehiculo = 69;
UPDATE vec_vehiculo_descripcion SET chunk_texto = $$Toyota Corolla 2022 negro mecánica hibrido 1.6L camioneta 16.106 km estado bueno$$ WHERE id_vehiculo = 70;
UPDATE vec_vehiculo_descripcion SET chunk_texto = $$Mazda CX-30 2021 azul profundo mecánica diesel 2L hatchback 70.671 km estado bueno$$ WHERE id_vehiculo = 71;
UPDATE vec_vehiculo_descripcion SET chunk_texto = $$Renault Sandero 2022 rojo milano mecánica gasolina 2.5L sedan 23.665 km estado excelente$$ WHERE id_vehiculo = 72;
UPDATE vec_vehiculo_descripcion SET chunk_texto = $$Toyota Hilux 2021 blanco automática gasolina 1.6L sedan 10.846 km estado bueno$$ WHERE id_vehiculo = 73;
UPDATE vec_vehiculo_descripcion SET chunk_texto = $$Mazda Mazda 3 2024 gris plata mecánica hibrido 2L hatchback 27.257 km estado bueno$$ WHERE id_vehiculo = 74;
UPDATE vec_vehiculo_descripcion SET chunk_texto = $$Chevrolet Colorado 2020 negro automática gasolina 1.6L hatchback 5.172 km estado bueno$$ WHERE id_vehiculo = 75;
UPDATE vec_vehiculo_descripcion SET chunk_texto = $$Chevrolet Onix 2024 negro mecánica gasolina 2.5L pickup 13.078 km estado muy_bueno$$ WHERE id_vehiculo = 76;
UPDATE vec_vehiculo_descripcion SET chunk_texto = $$Chevrolet Colorado 2022 gris plata automática gasolina 1.6L pickup 54.616 km estado bueno$$ WHERE id_vehiculo = 77;
UPDATE vec_vehiculo_descripcion SET chunk_texto = $$Renault Duster 2023 azul profundo automática gasolina 2.5L camioneta 31.052 km estado excelente$$ WHERE id_vehiculo = 78;
UPDATE vec_vehiculo_descripcion SET chunk_texto = $$Renault Kwid 2023 blanco automática hibrido 2L hatchback 33.483 km estado bueno$$ WHERE id_vehiculo = 79;
UPDATE vec_vehiculo_descripcion SET chunk_texto = $$Chevrolet Tracker 2021 negro mecánica diesel 1.6L pickup 57.971 km estado muy_bueno$$ WHERE id_vehiculo = 80;
UPDATE vec_vehiculo_descripcion SET chunk_texto = $$Mazda Mazda 3 2023 azul profundo automática diesel 1.6L camioneta 8.590 km estado bueno$$ WHERE id_vehiculo = 81;
UPDATE vec_vehiculo_descripcion SET chunk_texto = $$Mazda CX-5 2021 negro mecánica diesel 1.6L sedan 18.254 km estado bueno$$ WHERE id_vehiculo = 82;
UPDATE vec_vehiculo_descripcion SET chunk_texto = $$Renault Kwid 2020 gris plata mecánica hibrido 2.5L pickup 35.286 km estado bueno$$ WHERE id_vehiculo = 83;
UPDATE vec_vehiculo_descripcion SET chunk_texto = $$Renault Kwid 2018 negro automática diesel 2.5L camioneta 70.792 km estado bueno$$ WHERE id_vehiculo = 84;
UPDATE vec_vehiculo_descripcion SET chunk_texto = $$Chevrolet Onix 2019 blanco mecánica gasolina 2L pickup 69.567 km estado bueno$$ WHERE id_vehiculo = 85;
UPDATE vec_vehiculo_descripcion SET chunk_texto = $$Renault Logan 2022 azul profundo mecánica gasolina 2L sedan 53.350 km estado bueno$$ WHERE id_vehiculo = 86;
UPDATE vec_vehiculo_descripcion SET chunk_texto = $$Toyota Fortuner 2025 gris plata mecánica hibrido 1.6L sedan 31.658 km estado muy_bueno$$ WHERE id_vehiculo = 87;
UPDATE vec_vehiculo_descripcion SET chunk_texto = $$Mazda CX-30 2020 gris plata automática hibrido 1.6L sedan 14.519 km estado excelente$$ WHERE id_vehiculo = 88;
UPDATE vec_vehiculo_descripcion SET chunk_texto = $$Renault Sandero 2020 gris plata automática gasolina 1.6L sedan 9.613 km estado excelente$$ WHERE id_vehiculo = 89;
UPDATE vec_vehiculo_descripcion SET chunk_texto = $$Chevrolet Onix 2021 negro mecánica hibrido 1.6L suv 34.197 km estado bueno$$ WHERE id_vehiculo = 90;
UPDATE vec_vehiculo_descripcion SET chunk_texto = $$Renault Kwid 2023 rojo milano automática hibrido 1.6L camioneta 50.954 km estado muy_bueno$$ WHERE id_vehiculo = 91;
UPDATE vec_vehiculo_descripcion SET chunk_texto = $$Mazda CX-30 2019 rojo milano automática diesel 2L sedan 48.812 km estado excelente$$ WHERE id_vehiculo = 92;
UPDATE vec_vehiculo_descripcion SET chunk_texto = $$Toyota Hilux 2018 blanco mecánica hibrido 2.5L camioneta 86.223 km estado muy_bueno$$ WHERE id_vehiculo = 93;
UPDATE vec_vehiculo_descripcion SET chunk_texto = $$Mazda CX-30 2019 negro mecánica gasolina 2L pickup 67.934 km estado bueno$$ WHERE id_vehiculo = 94;
UPDATE vec_vehiculo_descripcion SET chunk_texto = $$Renault Kwid 2025 negro mecánica diesel 2.5L hatchback 74.115 km estado excelente$$ WHERE id_vehiculo = 95;
UPDATE vec_vehiculo_descripcion SET chunk_texto = $$Toyota Corolla 2023 azul profundo automática hibrido 1.6L suv 56.042 km estado muy_bueno$$ WHERE id_vehiculo = 96;
UPDATE vec_vehiculo_descripcion SET chunk_texto = $$Chevrolet Onix 2024 gris plata automática diesel 2.5L sedan 82.981 km estado bueno$$ WHERE id_vehiculo = 97;
UPDATE vec_vehiculo_descripcion SET chunk_texto = $$Chevrolet Colorado 2024 gris plata mecánica gasolina 2.5L camioneta 42.325 km estado excelente$$ WHERE id_vehiculo = 98;
UPDATE vec_vehiculo_descripcion SET chunk_texto = $$Chevrolet Tracker 2025 azul profundo automática hibrido 2.5L camioneta 52.545 km estado excelente$$ WHERE id_vehiculo = 99;
UPDATE vec_vehiculo_descripcion SET chunk_texto = $$Toyota Corolla 2025 rojo milano mecánica gasolina 2L camioneta 25.676 km estado excelente$$ WHERE id_vehiculo = 100;
UPDATE vec_vehiculo_descripcion SET chunk_texto = $$Chevrolet Captiva 2022 negro automática hibrido 2L suv 42.907 km estado muy_bueno$$ WHERE id_vehiculo = 101;
UPDATE vec_vehiculo_descripcion SET chunk_texto = $$Chevrolet Colorado 2023 rojo milano mecánica diesel 1.6L hatchback 28.627 km estado excelente$$ WHERE id_vehiculo = 102;
UPDATE vec_vehiculo_descripcion SET chunk_texto = $$Mazda CX-30 2019 gris plata automática hibrido 2.5L hatchback 63.791 km estado excelente$$ WHERE id_vehiculo = 103;
UPDATE vec_vehiculo_descripcion SET chunk_texto = $$Chevrolet Tracker 2019 blanco mecánica gasolina 1.6L pickup 65.276 km estado bueno$$ WHERE id_vehiculo = 104;
UPDATE vec_vehiculo_descripcion SET chunk_texto = $$Mazda CX-5 2019 azul profundo mecánica diesel 2L camioneta 50.747 km estado muy_bueno$$ WHERE id_vehiculo = 105;
UPDATE vec_vehiculo_descripcion SET chunk_texto = $$Renault Sandero 2019 gris plata mecánica diesel 2L suv 56.647 km estado bueno$$ WHERE id_vehiculo = 106;
UPDATE vec_vehiculo_descripcion SET chunk_texto = $$Mazda Mazda 3 2025 azul profundo mecánica diesel 1.6L hatchback 38.054 km estado muy_bueno$$ WHERE id_vehiculo = 107;
UPDATE vec_vehiculo_descripcion SET chunk_texto = $$Toyota Fortuner 2019 rojo milano automática gasolina 2L pickup 48.623 km estado excelente$$ WHERE id_vehiculo = 108;
UPDATE vec_vehiculo_descripcion SET chunk_texto = $$Toyota Corolla 2025 blanco automática diesel 1.6L suv 48.967 km estado bueno$$ WHERE id_vehiculo = 109;
UPDATE vec_vehiculo_descripcion SET chunk_texto = $$Chevrolet Tracker 2024 blanco automática diesel 2L sedan 62.201 km estado muy_bueno$$ WHERE id_vehiculo = 110;
UPDATE vec_vehiculo_descripcion SET chunk_texto = $$Chevrolet Tracker 2022 negro mecánica gasolina 2L suv 12.370 km estado muy_bueno$$ WHERE id_vehiculo = 111;
UPDATE vec_vehiculo_descripcion SET chunk_texto = $$Chevrolet Captiva 2022 negro automática diesel 2L sedan 68.033 km estado bueno$$ WHERE id_vehiculo = 112;
UPDATE vec_vehiculo_descripcion SET chunk_texto = $$Mazda CX-30 2023 azul profundo mecánica hibrido 2L camioneta 72.605 km estado bueno$$ WHERE id_vehiculo = 113;
UPDATE vec_vehiculo_descripcion SET chunk_texto = $$Chevrolet Colorado 2022 negro automática hibrido 2L pickup 38.715 km estado excelente$$ WHERE id_vehiculo = 114;
UPDATE vec_vehiculo_descripcion SET chunk_texto = $$Mazda CX-30 2023 rojo milano automática diesel 2.5L pickup 40.385 km estado muy_bueno$$ WHERE id_vehiculo = 115;
UPDATE vec_vehiculo_descripcion SET chunk_texto = $$Chevrolet Captiva 2023 rojo milano mecánica hibrido 2.5L camioneta 17.923 km estado bueno$$ WHERE id_vehiculo = 116;
UPDATE vec_vehiculo_descripcion SET chunk_texto = $$Chevrolet Onix 2020 gris plata automática gasolina 1.6L sedan 25.311 km estado muy_bueno$$ WHERE id_vehiculo = 117;
UPDATE vec_vehiculo_descripcion SET chunk_texto = $$Renault Duster 2022 negro automática diesel 2.5L pickup 53.226 km estado excelente$$ WHERE id_vehiculo = 118;
UPDATE vec_vehiculo_descripcion SET chunk_texto = $$Mazda CX-5 2019 negro mecánica diesel 2.5L suv 70.661 km estado muy_bueno$$ WHERE id_vehiculo = 119;
UPDATE vec_vehiculo_descripcion SET chunk_texto = $$Mazda Mazda 3 2023 rojo milano mecánica hibrido 2L suv 36.541 km estado muy_bueno$$ WHERE id_vehiculo = 120;
UPDATE vec_vehiculo_descripcion SET chunk_texto = $$Chevrolet Onix 2022 blanco automática gasolina 2.5L hatchback 26.997 km estado excelente$$ WHERE id_vehiculo = 121;
UPDATE vec_vehiculo_descripcion SET chunk_texto = $$Renault Duster 2022 gris plata mecánica gasolina 1.6L pickup 82.473 km estado bueno$$ WHERE id_vehiculo = 122;
UPDATE vec_vehiculo_descripcion SET chunk_texto = $$Chevrolet Captiva 2019 blanco automática diesel 2.5L hatchback 42.742 km estado muy_bueno$$ WHERE id_vehiculo = 123;
UPDATE vec_vehiculo_descripcion SET chunk_texto = $$Mazda CX-30 2023 gris plata mecánica diesel 1.6L camioneta 24.229 km estado bueno$$ WHERE id_vehiculo = 124;
UPDATE vec_vehiculo_descripcion SET chunk_texto = $$Mazda CX-5 2021 blanco mecánica diesel 1.6L suv 75.693 km estado muy_bueno$$ WHERE id_vehiculo = 125;
UPDATE vec_vehiculo_descripcion SET chunk_texto = $$Mazda Mazda 3 2020 negro automática gasolina 2L sedan 5.642 km estado muy_bueno$$ WHERE id_vehiculo = 126;
UPDATE vec_vehiculo_descripcion SET chunk_texto = $$Toyota Yaris 2021 negro mecánica gasolina 1.6L sedan 77.385 km estado bueno$$ WHERE id_vehiculo = 127;
UPDATE vec_vehiculo_descripcion SET chunk_texto = $$Mazda Mazda 3 2018 negro mecánica gasolina 2L suv 40.848 km estado bueno$$ WHERE id_vehiculo = 128;
UPDATE vec_vehiculo_descripcion SET chunk_texto = $$Chevrolet Onix 2024 blanco mecánica hibrido 2.5L camioneta 69.597 km estado excelente$$ WHERE id_vehiculo = 129;
UPDATE vec_vehiculo_descripcion SET chunk_texto = $$Renault Kwid 2023 gris plata automática diesel 2L pickup 73.990 km estado bueno$$ WHERE id_vehiculo = 130;
UPDATE vec_vehiculo_descripcion SET chunk_texto = $$Mazda Mazda 3 2019 azul profundo mecánica hibrido 1.6L camioneta 17.015 km estado bueno$$ WHERE id_vehiculo = 131;
UPDATE vec_vehiculo_descripcion SET chunk_texto = $$Toyota Corolla 2019 gris plata automática diesel 2.5L pickup 89.868 km estado bueno$$ WHERE id_vehiculo = 132;
UPDATE vec_vehiculo_descripcion SET chunk_texto = $$Toyota Hilux 2024 blanco automática diesel 2L sedan 67.161 km estado muy_bueno$$ WHERE id_vehiculo = 133;
UPDATE vec_vehiculo_descripcion SET chunk_texto = $$Mazda CX-30 2018 blanco mecánica gasolina 2L camioneta 21.702 km estado excelente$$ WHERE id_vehiculo = 134;
UPDATE vec_vehiculo_descripcion SET chunk_texto = $$Chevrolet Captiva 2022 rojo milano mecánica gasolina 2.5L sedan 9.849 km estado bueno$$ WHERE id_vehiculo = 135;
UPDATE vec_vehiculo_descripcion SET chunk_texto = $$Toyota Fortuner 2022 blanco mecánica gasolina 1.6L pickup 34.994 km estado bueno$$ WHERE id_vehiculo = 136;
UPDATE vec_vehiculo_descripcion SET chunk_texto = $$Chevrolet Onix 2018 azul profundo mecánica gasolina 2.5L suv 21.233 km estado excelente$$ WHERE id_vehiculo = 137;
UPDATE vec_vehiculo_descripcion SET chunk_texto = $$Renault Duster 2022 rojo milano mecánica gasolina 2.5L sedan 15.361 km estado muy_bueno$$ WHERE id_vehiculo = 138;
UPDATE vec_vehiculo_descripcion SET chunk_texto = $$Toyota Corolla 2022 gris plata automática diesel 2L camioneta 72.583 km estado excelente$$ WHERE id_vehiculo = 139;
UPDATE vec_vehiculo_descripcion SET chunk_texto = $$Mazda Mazda 3 2020 negro mecánica hibrido 2.5L hatchback 80.593 km estado muy_bueno$$ WHERE id_vehiculo = 140;
UPDATE vec_vehiculo_descripcion SET chunk_texto = $$Toyota Corolla 2020 blanco automática diesel 1.6L pickup 82.941 km estado muy_bueno$$ WHERE id_vehiculo = 141;
UPDATE vec_vehiculo_descripcion SET chunk_texto = $$Renault Kwid 2022 rojo milano mecánica gasolina 2L pickup 80.716 km estado muy_bueno$$ WHERE id_vehiculo = 142;
UPDATE vec_vehiculo_descripcion SET chunk_texto = $$Mazda Mazda 2 2020 blanco automática hibrido 1.6L hatchback 59.142 km estado bueno$$ WHERE id_vehiculo = 143;
UPDATE vec_vehiculo_descripcion SET chunk_texto = $$Renault Logan 2023 gris plata automática diesel 2.5L suv 61.651 km estado bueno$$ WHERE id_vehiculo = 144;
UPDATE vec_vehiculo_descripcion SET chunk_texto = $$Toyota Fortuner 2023 azul profundo mecánica gasolina 1.6L pickup 51.287 km estado bueno$$ WHERE id_vehiculo = 145;
UPDATE vec_vehiculo_descripcion SET chunk_texto = $$Renault Kwid 2023 negro mecánica hibrido 2.5L suv 12.876 km estado excelente$$ WHERE id_vehiculo = 146;
UPDATE vec_vehiculo_descripcion SET chunk_texto = $$Toyota Fortuner 2020 gris plata automática diesel 2.5L camioneta 7.435 km estado bueno$$ WHERE id_vehiculo = 147;
UPDATE vec_vehiculo_descripcion SET chunk_texto = $$Renault Duster 2021 blanco mecánica hibrido 2L camioneta 77.763 km estado muy_bueno$$ WHERE id_vehiculo = 148;
UPDATE vec_vehiculo_descripcion SET chunk_texto = $$Chevrolet Onix 2018 azul profundo mecánica diesel 2.5L sedan 54.141 km estado bueno$$ WHERE id_vehiculo = 149;
UPDATE vec_vehiculo_descripcion SET chunk_texto = $$Renault Duster 2018 blanco mecánica gasolina 1.6L pickup 48.003 km estado muy_bueno$$ WHERE id_vehiculo = 150;

COMMIT;

-- ============================================================
-- Después de este script, regenerar embeddings para los 150
-- registros de vec_vehiculo_descripcion.
-- Para invalidar embeddings viejos explícitamente:
--   UPDATE vec_vehiculo_descripcion SET embedding = NULL;
-- ============================================================
